"""wallet model update

Revision ID: 4944187c2346
Revises: d190f7b3a2c1
Create Date: 2026-10-02 11:29:17.809631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4944187c2346'
down_revision: Union[str, Sequence[str], None] = 'd190f7b3a2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('account_number', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'wallet', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_column('wallet', 'account_number')
    # ### end Alembic commands ###
