"""wallet-model

Revision ID: 5223c6c11fb9
Revises: 
Create Date: 2026-09-25 05:59:28.088600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5223c6c11fb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entries_amount', sa.Float(), nullable=False),
    sa.Column('account_owners_type', sa.String(), nullable=False),
    sa.Column('entries_id', sa.String(), nullable=True),
    sa.Column('entries_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('transaction_pin', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wallet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wallet_userId', sa.String(), nullable=True),
    sa.Column('wallet_currency', sa.String(), nullable=False),
    sa.Column('wallet_available_balance', sa.Float(), nullable=False),
    sa.Column('wallet_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_userId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('user')
    op.drop_table('ledger')
    # ### end Alembic commands ###
