""" model

Revision ID: 749a7ca270e2
Revises: 
Create Date: 2026-10-08 14:48:16.569733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749a7ca270e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('transaction_pin', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('session',
    sa.Column('sessionId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('sessionId')
    )
    op.create_table('wallet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('wallet_userId', sa.String(), nullable=True),
    sa.Column('wallet_currency', sa.String(), nullable=False),
    sa.Column('wallet_available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('wallet_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('wallet_userId')
    )
    op.create_table('ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entries_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account_owners_type', sa.String(), nullable=False),
    sa.Column('entries_id', sa.String(), nullable=False),
    sa.Column('entries_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entries_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_status', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_reference', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('sender_wallet_id', sa.String(), nullable=False),
    sa.Column('receiver_wallet_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['wallet.wallet_currency'], ),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_reference'),
    sa.UniqueConstraint('transaction_reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('ledger')
    op.drop_table('wallet')
    op.drop_table('session')
    op.drop_table('user')
    # ### end Alembic commands ###
